### ISSUE TITLE
不太理解为什么要53333:23333

### ISSUE THREAD

**Issue by shentong0722** [Ink-Osier/getPandoraLicenseUsage#1]
如题，不太理解为什么要53333端口映射23333端口

**Comment by Ink-Osier** [comment]
`23333` 只是我给Flask设置的端口，不喜欢 `53333` 的话可以修改成任意端口

**Comment by shentong0722** [comment]
这个报错是为啥捏：
![image](https://github.com/Ink-Osier/getPandoraLicenseUsage/assets/63089521/ec4f2162-8736-4e68-a4ec-01c758653f02)
日志信息：
![image](https://github.com/Ink-Osier/getPandoraLicenseUsage/assets/63089521/803b4f95-f37f-41a1-8600-d9f4b3eb301c)

**Comment by Ink-Osier** [comment]
检查一下你的license_id是否设置正确以及这个项目是否和你的pandoranext部署在了同一台服务器，以及pandoranext项目是否使用了代理

**Comment by shentong0722** [comment]
> 检查一下你的license_id是否设置正确以及这个项目是否和你的pandoranext部署在了同一台服务器，以及pandoranext项目是否使用了代理

是同一台且没有代理，都是用docker部署的

**Comment by Ink-Osier** [comment]
更新一下最新版的这个项目，然后看看错误提示是什么

**Comment by shentong0722** [comment]
> 更新一下最新版的这个项目，然后看看错误提示是什么

就是刚部署的呀啊。肯定是最新版的，错误提示我截图里有

**Comment by Ink-Osier** [comment]
刚刚升级的0.0.3版本，优化了错误提示，你这个应该是0.0.2版本的

**Comment by shentong0722** [comment]
> 刚刚升级的0.0.3版本，优化了错误提示，你这个应该是0.0.2版本的

更新过后的报错信息是这样的：
![image](https://github.com/Ink-Osier/getPandoraLicenseUsage/assets/63089521/d96b3c92-ed31-4671-878d-ef3d704cd72a)

无法从 Pandora Next 获取数据，状态码：403, 响应：{"detail":"Forbidden"}
23.94.221.108 - - [17/Dec/2023 08:03:25] "GET /api/getPandoraNextLicUsage HTTP/1.1" 500 -

**Comment by Ink-Osier** [comment]
嗯 那建议还是检查一下：

1. PANDORA_LICENSE_ID的值是不是对的（注意要输入的是id，不是证书本身）
2. 这个容器的公网出口ip和pandora的公网出口ip是不是用的一个ip
 
一般出现这个问题就是这两个地方可能出问题。

**Comment by Ink-Osier** [comment]
以及，刚刚又推送了一个新版本0.0.4，在出错的时候容器的日志里会显示一个pandora的链接，你可以试试在你同一台服务器上手动访问一下那个链接看看会响应什么内容

**Comment by shentong0722** [comment]
> 嗯 那建议还是检查一下：
> 
> 1. PANDORA_LICENSE_ID的值是不是对的（注意要输入的是id，不是证书本身）
> 2. 这个容器的公网出口ip和pandora的公网出口ip是不是用的一个ip
> 
> 一般出现这个问题就是这两个地方可能出问题。

1、确定ID是正确的
2、
![image](https://github.com/Ink-Osier/getPandoraLicenseUsage/assets/63089521/6bca47e5-80f9-469a-897e-18d240e0f0c1)
容器出口IP难道不都是公网出口IP吗，Pandora也没在列表里

**Comment by shentong0722** [comment]
> 以及，刚刚又推送了一个新版本0.0.4，在出错的时候容器的日志里会显示一个pandora的链接，你可以试试在你同一台服务器上手动访问一下那个链接看看会响应什么内容

升级了，但是结果是一样的，输出多了一行链接点了也是forbidden

**Comment by Ink-Osier** [comment]
怪怪的，感觉就是ip的问题，可以检查一下pandora启动的时候日志输出的ip和你在同服务器curl ip.sb输出的ip是否是一样的。

**Comment by shentong0722** [comment]
好家伙折腾了半天是License Id的问题，刷新了一下就好了

**Comment by Ink-Osier** [comment]
手动狗头，点个星星吧
